export const lsEmail = "_VMAHl01uTen3a65";
export const lsPassword = "_OlIHQZIEonuFt1c";
export const lsToken = "_XnbbLOcIG01N556";
export const lsForgetToken = "_lpiSIrjrOi";
export const lsForgetEmail = "_pzCp2vCcTP";

export const contactFormUUID = "contact-form";
export const companyFormUUID = "company-form";
export const opportunityFormUUID = "opportunity-form";
export const meetingFormUUID = "meeting-form";
export const taskFormUUID = "task-form";

export const leadStatuses = [
  "New Lead",
  "Contacted",
  "Qualified",
  "Engaged",
  "Negotiation",
  "Closed-Won",
  "Closed-Lost",
];

export const customerTypes = [
  "New Customers",
  "Existing Customers",
  "Potential Customers",
  "Qualified Leads",
  "Lost Customers",
  "Referral Customers",
  "Cold Leads",
  "Warm Leads",
  "Hot Leads",
  "VIP Customers",
];

export const companyTypes = [
  "B2B",
  "B2C",
  "Retail",
  "Education",
  "NonProfit",
  "Technology",
  "Government",
  "Healthcare",
  "Real Estate",
  "Manufacturing",
  "Financial Services",
];

export const countries = ["India", "USA", "Canada", "Australia"];

export const states = [
  "New South Wales",
  "Victoria",
  "Queensland",
  "Western Australia",
  "South Australia",
  "Ontario",
  "Quebec",
  "British Columbia",
  "Alberta",
  "Manitoba",
  "California",
  "New York",
  "Texas",
  "Florida",
  "Illinois",
  "Maharashtra",
  "Karnataka",
  "Tamil Nadu",
  "Uttar Pradesh",
  "Gujarat",
];

export const cities = [
  "Mumbai",
  "Pune",
  "Nagpur",
  "Nashik",
  "Thane",
  "Aurangabad",
  "Bangalore",
  "Mysore",
  "Hubli",
  "Mangalore",
  "Belgaum",
  "Gulbarga",
  "Chennai",
  "Coimbatore",
  "Madurai",
  "Tiruchirappalli",
  "Salem",
  "Tiruppur",
  "Lucknow",
  "Kanpur",
  "Agra",
  "Varanasi",
  "Allahabad",
  "Ghaziabad",
  "Ahmedabad",
  "Surat",
  "Vadodara",
  "Rajkot",
  "Bhavnagar",
  "Jamnagar",
  "Manhattan",
  "Brooklyn",
  "Queens",
  "Bronx",
  "Houston",
  "Dallas",
  "Austin",
  "San Antonio",
  "Miami",
  "Orlando",
  "Tampa",
  "Jacksonville",
  "Chicago",
  "Springfield",
  "Peoria",
  "Rockford",
  "Los Angeles",
  "San Francisco",
  "San Diego",
  "Sacramento",
  "Sydney",
  "Newcastle",
  "Wollongong",
  "Melbourne",
  "Geelong",
  "Ballarat",
  "Brisbane",
  "Gold Coast",
  "Sunshine Coast",
  "Perth",
  "Mandurah",
  "Bunbury",
  "Adelaide",
  "Mount Gambier",
  "Whyalla",
  "Calgary",
  "Edmonton",
  "Red Deer",
  "Lethbridge",
  "Medicine Hat",
  "Winnipeg",
  "Brandon",
  "Steinbach",
  "Portage la Prairie",
  "Thompson",
  "Montreal",
  "Quebec City",
  "Laval",
  "Gatineau",
  "Longueuil",
  "Vancouver",
  "Surrey",
  "Burnaby",
  "Richmond",
  "Kelowna",
  "Toronto",
  "Ottawa",
  "Mississauga",
  "Hamilton",
  "London",
];

export const meetingAttendesContact = [
  { value: "ABC", label: "ABC" },
  { value: "XYZ", label: "XYZ" },
]

