import { FormValuesType } from "@/common/utils/formTypes";

const companies: FormValuesType[] | [] = [
  {
    id: "76d11053-8a53-483a-8c6a-2a64681ca24a",
    company_name: "ABC Company",
    company_size: "101",
    company_type: "b2b",
    company_phone: "9876543210",
    company_email: "abc@example.com",
    company_website: "www.abc.com",
    company_description: "This is a description of ABC Company.",
    billing_pin: "123456",
    billing_city: "pune",
    billing_state: "maharashtra",
    billing_country: "india",
    billing_address_first: "123 Street",
    billing_address_second: "Apt 1",
    shipping_pin: "123456",
    shipping_city: "pune",
    shipping_state: "maharashtra",
    shipping_country: "india",
    shipping_address_first: "123 Street",
    shipping_address_second: "Apt 1",
    created_by: "1",
  },
  {
    id: "4e9175b8-347b-474b-abcd-d646be5c196c",
    created_by: "1",
    company_size: "101",
    company_type: "b2b",
    billing_city: "pune",
    billing_pin: "654321",
    shipping_city: "pune",
    shipping_pin: "654321",
    billing_country: "india",
    company_name: "XYZ Corp",
    shipping_country: "india",
    company_phone: "9876543210",
    billing_state: "maharashtra",
    shipping_state: "maharashtra",
    company_email: "xyz@example.com",
    billing_address_second: "Suite 2",
    shipping_address_second: "Suite 2",
    company_website: "www.xyzcorp.com",
    billing_address_first: "456 Avenue",
    shipping_address_first: "456 Avenue",
    company_description: "This is a description of XYZ Corp.",
  },
  {
    id: "bd317b1d-dc8f-4387-b487-afe5e66de01e",
    company_name: "PQR Ltd",
    company_size: "101",
    company_type: "technology",
    company_phone: "9876543210",
    company_email: "pqr@example.com",
    company_website: "www.pqr-ltd.com",
    company_description: "This is a description of PQR Ltd.",
    billing_pin: "987654",
    billing_city: "pune",
    billing_state: "maharashtra",
    billing_country: "india",
    billing_address_first: "789 Road",
    billing_address_second: "Unit 3",
    shipping_pin: "987654",
    shipping_city: "pune",
    shipping_state: "maharashtra",
    shipping_country: "india",
    shipping_address_first: "789 Road",
    shipping_address_second: "Unit 3",
    created_by: "1",
  },
  {
    id: "5e39eb8e-93a9-4f43-b21d-226f720e0f0d",
    company_name: "LMN Enterprises",
    company_size: "101",
    company_type: "technology",
    company_phone: "9876543210",
    company_email: "lmn@example.com",
    company_website: "www.lmn-ent.com",
    company_description: "This is a description of LMN Enterprises.",
    billing_pin: "456789",
    billing_city: "pune",
    billing_state: "maharashtra",
    billing_country: "india",
    billing_address_first: "101 Boulevard",
    billing_address_second: "Floor 4",
    shipping_pin: "456789",
    shipping_city: "pune",
    shipping_state: "maharashtra",
    shipping_country: "india",
    shipping_address_first: "101 Boulevard",
    shipping_address_second: "Floor 4",
    created_by: "1",
  },
  {
    id: "df82b9df-78cc-432d-ae77-bbdff2f06696",
    company_name: "RST Inc",
    company_size: "101",
    company_type: "b2b",
    company_phone: "9876543210",
    company_email: "rst@example.com",
    company_website: "www.rstinc.com",
    company_description: "This is a description of RST Inc.",
    billing_pin: "222333",
    billing_city: "pune",
    billing_state: "maharashtra",
    billing_country: "india",
    billing_address_first: "202 Lane",
    billing_address_second: "Apt 5",
    shipping_pin: "222333",
    shipping_city: "pune",
    shipping_state: "maharashtra",
    shipping_country: "india",
    shipping_address_first: "202 Lane",
    shipping_address_second: "Apt 5",
    created_by: "1",
  },
];
export default companies;
