import { Contact } from "@/types/contacts.types";

const contactsData: Contact[] = [
  {
    id: "2a69b1c7-f0f6-4f08-8aef-7f8cf4009e9f",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user1@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "John",
    jobTitle: "Developer",
    lastName: "Doe",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "45f05ad4-1b33-493b-83c7-d68b1c18ee65",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user2@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Jane",
    jobTitle: "Developer",
    lastName: "Smith",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "a1e38462-d5d3-472f-8b14-3b7cd2cc9d90",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user3@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Michael",
    jobTitle: "Developer",
    lastName: "Johnson",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "f6ab1ad5-1e33-484c-b23f-2647c0d33e91",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user4@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Emily",
    jobTitle: "Developer",
    lastName: "Brown",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "3dcd9c7b-19d4-4391-bf5f-67c4c9d3f324",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user5@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Jessica",
    jobTitle: "Developer",
    lastName: "Lee",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "2a69b1c7-f0f6-4f08-8aef-7f8cf4009e9fa",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user6@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Johhn",
    jobTitle: "Developer",
    lastName: "Dov",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "45f05ad4-1b33-493b-83c7-d68b1c18ee65b",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user7@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Janey",
    jobTitle: "Developer",
    lastName: "Smith",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "a1e38462-d5d3-472f-8b14-3b7cd2cc9d90c",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user8@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Michael",
    jobTitle: "Developer",
    lastName: "Johnson",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "f6ab1ad5-1e33-484c-b23f-2647c0d33e91d",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user9@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Emilyie",
    jobTitle: "Developer",
    lastName: "Brown",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "3dcd9c7b-19d4-4391-bf5f-67c4c9d3f324e",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user10@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Jessica",
    jobTitle: "Developer",
    lastName: "Lee",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "2a69b1c7-f0f6-4f08-8aef-7f8cf4009e9faf",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user11@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Johhy",
    jobTitle: "Developer",
    lastName: "Dov",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "45f05ad4-1b33-493b-83c7-d68b1c18ee65bg",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user12@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Janeie",
    jobTitle: "Developer",
    lastName: "Smith",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "a1e38462-d5d3-472f-8b14-3b7cd2cc9d90ch",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user13@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Michaell",
    jobTitle: "Developer",
    lastName: "Johnson",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "f6ab1ad5-1e33-484c-b23f-2647c0d33e91di",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user14@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Emilyyye",
    jobTitle: "Developer",
    lastName: "Brown",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "3dcd9c7b-19d4-4391-bf5f-67c4c9d3f324ej",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user15@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Jessiccaa",
    jobTitle: "Developer",
    lastName: "Lee",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
  {
    id: "3dcd9c7b-19d4-4391-bf5f-67c4c9d3f324ek",
    address: "Near IT park Panchkula",
    birthday: "2024-03-21",
    communicationChannel: "Skype",
    department: "Information Technology",
    email: "user16@gmail.com",
    facebook: "http://loream.picsum.com",
    firstName: "Jessikka",
    jobTitle: "Developer",
    lastName: "Lee",
    linkedin: "http://loream.picsum.com",
    notes: "Hello, this is the first note of me",
    phoneNumber: "9786543210",
    twitter: "http://loream.picsum.com",
    createdBy: "1",
  },
];

export default contactsData;
